arch:
  - amd64
  - ppc64le
sudo: false
language: go
go:
  - 1.14.x
  - 1.17.x
  - master
  
install:
  - go mod download

script:
  - go test -v -race ./...

matrix:
  allow_failures:
    - go: master
  fast_finish: true
